### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gittrainee323**
# Gittrainee323

New branch from Gittrainee323

### CODE REVIEW

**Comment by barry323** [comment]
Comment from barry323

**Comment by gittrainee323** [comment]
Comment from Gittrainee323

**Comment by gittrainee323** [comment]
Comment 2 from Gittrainee323

**Comment by barry323** [comment]
Comment 2 from barry323

**Comment by gittrainee323** [comment]
Comment 3 from Gittrainee323

**Comment by gittrainee323** [comment]
Comment 4 from Gittrainee323

**Comment by barry323** [comment]
- [x] Task Item 1
- [x] Task Item 2
- [x] Task Item 3
- [ ] Task Item 4
  - [ ] Task Item 4.1
  - [x] Task Item 4.2
- [x] Task Item 5

**Pull request closed without merging**
